In [34]:
import pandas as pd
import numpy as np

In [35]:
from pycaret.datasets import get_data
all_datasets = get_data('index')

,Dataset,Data Types,Default Task,Target Variable 1,Target Variable 2,# Instances,# Attributes,Missing Values
0,anomaly,Multivariate,Anomaly Detection,None,None,1000,10,N
1,france,Multivariate,Association Rule Mining,InvoiceNo,Description,8557,8,N
2,germany,Multivariate,Association Rule Mining,InvoiceNo,Description,9495,8,N
3,bank,Multivariate,Classification (Binary),deposit,None,45211,17,N
4,blood,Multivariate,Classification (Binary),Class,None,748,5,N
5,cancer,Multivariate,Classification (Binary),Class,None,683,10,N
6,credit,Multivariate,Classification (Binary),default,None,24000,24,N
7,diabetes,Multivariate,Classification (Binary),Class variable,None,768,9,N
8,electrical_grid,Multivariate,Classification (Binary),stabf,None,10000,14,N
9,employee,Multivariate,Classification (Binary),left,None,14999,10,N
10,heart,Multivariate,Classification (Binary),DEATH,None,200,16,N
11,heart_disease,Multivariate,Classification (Binary),Disease,None,270,14,N
12,hepatitis,Multivariate,Classification (Binary),Class,None,154,32,Y
13,income,Multivariate,Classification (Binary),income >50K,None,32561,14,Y
14,juice,Multivariate,Classification (Binary),Purchase,None,1070,15,N
15,nba,Multivariate,Classification (Binary),TARGET_5Yrs,None,1340,21,N
16,wine,Multivariate,Classification (Binary),type,None,6498,13,N
17,telescope,Multivariate,Classification (Binary),Class,None,19020,11,N
18,titanic,Multivariate,Classification (Binary),Survived,None,891,11,Y
19,us_presidential_election_results,Multivariate,Classification (Binary),party_winner,None,497,7,N
20,glass,Multivariate,Classification (Multiclass),Type,None,214,10,N
21,iris,Multivariate,Classification (Multiclass),species,None,150,5,N
22,poker,Multivariate,Classification (Multiclass),CLASS,None,100000,11,N
23,questions,Multivariate,Classification (Multiclass),Next_Question,None,499,4,N
24,satellite,Multivariate,Classification (Multiclass),Class,None,6435,37,N
25,CTG,Multivariate,Classification (Multiclass),NSP,None,2129,40,Y
26,asia_gdp,Multivariate,Clustering,None,None,40,11,N
27,elections,Multivariate,Clustering,None,None,3195,54,Y
28,facebook,Multivariate,Clustering,None,None,7050,12,N
29,ipl,Multivariate,Clustering,None,None,153,25,N
30,jewellery,Multivariate,Clustering,None,None,505,4,N
31,mice,Multivariate,Clustering,None,None,1080,82,Y
32,migration,Multivariate,Clustering,None,None,233,12,N
33,perfume,Multivariate,Clustering,None,None,20,29,N
34,pokemon,Multivariate,Clustering,None,None,800,13,Y
35,population,Multivariate,Clustering,None,None,255,56,Y
36,public_health,Multivariate,Clustering,None,None,224,21,N
37,seeds,Multivariate,Clustering,None,None,210,7,N
38,wholesale,Multivariate,Clustering,None,None,440,8,N
39,tweets,Text,NLP,tweet,None,8594,2,N
40,amazon,Text,NLP / Classification,reviewText,None,20000,2,N
41,kiva,Text,NLP / Classification,en,None,6818,7,N
42,spx,Text,NLP / Regression,text,None,874,4,N
43,wikipedia,Text,NLP / Classification,Text,None,500,3,N
44,automobile,Multivariate,Regression,price,None,202,26,Y
45,bike,Multivariate,Regression,cnt,None,17379,15,N
46,boston,Multivariate,Regression,medv,None,506,14,N
47,concrete,Multivariate,Regression,strength,None,1030,9,N
48,diamond,Multivariate,Regression,Price,None,6000,8,N
49,energy,Multivariate,Regression,Heating Load,Cooling Load,768,10,N
50,forest,Multivariate,Regression,area,None,517,13,N
51,gold,Multivariate,Regression,Gold_T+22,None,2558,121,N
52,house,Multivariate,Regression,SalePrice,None,1461,81,Y
53,insurance,Multivariate,Regression,charges,None,1338,7,N
54,parkinsons,Multivariate,Regression,PPE,None,5875,22,N
55,traffic,Multivariate,Regression,traffic_volume,None,48204,8,N

In [3]:
diamond = get_data('diamond')

   Carat Weight    Cut Color Clarity Polish Symmetry Report  Price
0          1.10  Ideal     H     SI1     VG       EX    GIA   5169
1          0.83  Ideal     H     VS1     ID       ID   AGSL   3470
2          0.85  Ideal     H     SI1     EX       EX    GIA   3183
3          0.91  Ideal     E     SI1     VG       VG    GIA   4370
4          0.83  Ideal     G     SI1     EX       EX    GIA   3171

In [32]:
from pycaret.regression import *

In [12]:
seen = diamond.sample(frac=0.8,random_state=200) #random state is a seed value
unseen = diamond.drop(seen.index)

In [13]:
seen.shape

(4800, 8)

In [14]:
unseen.shape

(1200, 8)

In [36]:
s = setup(data = seen, target = 'Price', session_id = 2)

In [8]:
best = compare_models()

In [11]:
best_mae = compare_models(sort = 'MAE')

In [17]:
evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [24]:
pred1 = predict_model(best, data = unseen)

In [28]:
tuned_best = tune_model(best)

In [37]:
evaluate_model(tuned_best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [30]:
pred2 = predict_model(tuned_best, data = unseen)

In [18]:
top3 = compare_models(n_select = 3)

In [20]:
top3

[ExtraTreesRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mse',
                     max_depth=None, max_features='auto', max_leaf_nodes=None,
                     max_samples=None, min_impurity_decrease=0.0,
                     min_impurity_split=None, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=2, verbose=0, warm_start=False),
 RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       max_samples=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=2, verbose=0, warm_start=False),
 GradientBoostingRegressor(alpha=0.9, ccp_alpha=0.0, criterion='friedman_mse',
                           init=None, learning_rate=0.1, loss='ls', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=2, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0, warm_start=False)]

In [21]:
stacker = stack_models(top3)

In [22]:
evaluate_model(stacker)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [31]:
pred3 = predict_model(stacker, data = unseen)

In [38]:
save_model(stacker, 'article_stacked_model_pipeline')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[], ml_usecase='regression',
                                       numerical_features=[], target='Price',
                                       time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_available',
                                 fill_value_categorical=None,
                                 fill_value_numerical=None,
                                 numeric_strategy='...
                                                                           min_samples_leaf=1,
                                                                           min_samples_split=2,
                                                                           min_weight_fraction_leaf=0.0,
                                                                           n_estimators=100,
                                                                           n_iter_no_change=None,
                                                                           presort='deprecated',
                                                                           random_state=2,
                                                                           subsample=1.0,
                                                                           tol=0.0001,
                                                                           validation_fraction=0.1,
                                                                           verbose=0,
                                                                           warm_start=False))],
                                    final_estimator=LinearRegression(copy_X=True,
                                                                     fit_intercept=True,
                                                                     n_jobs=-1,
                                                                     normalize=False),
                                    n_jobs=-1, passthrough=True, verbose=0)]],
          verbose=False),
 'article_stacked_model_pipeline.pkl')